{% set name = "yaqd-system-monitor" %}
{% set version = "2020.7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2be1853dfef68b1ba74c5fd77077f08694fbb41b7271ca1f010628474e9fe49a

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-system-monitor = yaqd_system_monitor._system_monitor:SystemMonitor.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - psutil
    - uptime
    - yaqd-core >=2020.7.3
    - flit
    - python >=3.7
  run:
    - psutil
    - python >=3.7
    - uptime
    - yaqd-core >=2020.7.3

test:
  imports:
    - yaqd_system_monitor
  commands:
    - pip check
    - yaqd-system-monitor --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemon for monitoring system usage
  dev_url: https://gitlab.com/yaq/yaqd-control
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
